// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xysim_moviedb.Models;

namespace xysimmoviedb.Migrations
{
    [DbContext(typeof(MvcMovieContext))]
    partial class MvcMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("xysim_moviedb.Models.Movie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("backdrop_path");

                    b.Property<string>("original_language");

                    b.Property<string>("original_title");

                    b.Property<string>("overview");

                    b.Property<float>("popularity");

                    b.Property<string>("poster_path");

                    b.Property<string>("release_date");

                    b.Property<string>("title");

                    b.Property<float>("vote_average");

                    b.Property<int>("vote_count");

                    b.HasKey("id");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
